#######################################################
##  .------..------..------..------..------..------.##
## |M.--. ||O.--. ||D.--. ||R.--. ||E.--. ||Q.--. | ##
## | (\/) || :/\: || :/\: || :(): || (\/) || (\/) | ##
## | :\/: || :\/: || (__) || ()() || :\/: || :\/: | ##
## | '--'M|| '--'O|| '--'D|| '--'R|| '--'E|| '--'Q| ##
##`------'`------'`------'`------'`------'`------'  ##
##                                                  ##
######################################################

## Information used to store request logs
database:
  mysql:
    table_prefix:
    username:
    password:
    database:
    port:
    host:

## Do not change, will break your settings
configVersion: 0.1